source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :production do
  gem 'unicorn', '5.4.1'
end

gem 'rails', '5.2.0'
gem 'sqlite3', '~> 1.3.6'
gem 'rmagick'
gem 'jwt'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]